AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Assign3 Demo
Parameters:
  FrontGitHubRepo:
    Type: String

  LambdaGitHubRepo:
    Type: String

  GitHubBranch:
    Type: String

  GitHubToken:
    Type: String

  GitHubUser:
    Type: String


Resources:


  LambdaDeployementS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: assign3lambda
      AccessControl: PublicRead
    DeletionPolicy: Delete

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PutBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref FrontS3Bucket
                - /*
      Bucket: !Ref FrontS3Bucket


  Lambda:
    Type: AWS::Serverless::Function
    DependsOn: 
      - LambdaPipeline
      - LambdaDeployementS3Bucket
    Properties:
      Environment:
        Variables:
          REGION: us-east-1
      CodeUri: 
        Bucket: !Ref LambdaDeployementS3Bucket
        Key: function/Assign3-LF1.zip  
      Description: Lambda function for FrontEnd 
      MemorySize: 128   

      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::186209955484:role/service-role/LFTEST-role-onewv07z
      Timeout: 30
      Runtime: python3.8
      FunctionName: assign3GenLF1

  Lambda2:
    Type: AWS::Serverless::Function
    DependsOn: 
      - LambdaPipeline
      - LambdaDeployementS3Bucket
    Properties:
      Environment:
        Variables:
          REGION: us-east-1
      CodeUri: 
        Bucket: !Ref LambdaDeployementS3Bucket
        Key: function/Assign3-LF2.zip 
      Description: Lambda function for CD Demo  
      MemorySize: 128   

      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::186209955484:role/service-role/LFTEST-role-onewv07z
      Timeout: 30
      Runtime: python3.8
      FunctionName: assign3GenLF2


Outputs:
  WebsiteURL:
    Value: !Join
    - ''
    - - !GetAtt 
        - FrontS3Bucket
        - WebsiteURL
      - '/page'
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - FrontS3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content