AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Assign3 Demo

Resources:
  
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          REGION: us-east-1
      CodeUri: 
        Bucket: assign3lambda
        Key: function/Assign3-LF1.zip  
      Description: Lambda function for FrontEnd 
      MemorySize: 128   

      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::186209955484:role/service-role/Assign3-LF1-role-kbq87fa8
      Timeout: 30
      Runtime: python3.8
      FunctionName: assign3GenLF1

  Lambda2:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          REGION: us-east-1
      CodeUri: 
        Bucket: assign3lambda
        Key: function/Assign3-LF2.zip 
      Description: Lambda function for CD Demo  
      MemorySize: 128   

      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::186209955484:role/service-role/Assign3-LF2-role-6c6jgmou
      Timeout: 30
      Runtime: python3.8
      FunctionName: assign3GenLF2